VALIDATION_ERROR = 400;
UNAUTHORIZED = 401;
FORBIDDEN = 403;
NOT_FOUND = 404;
TIME_OUT = 408;
SERVER_ERROR = 500;

module.exports = {
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  TIME_OUT,
  SERVER_ERROR,
};
